name: CI

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract Ngrok
        run: Expand-Archive ngrok.zip

      - name: Auth Ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Log in and Perform Actions
        run: |
          # Log in
          $securePassword = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
          $credentials = New-Object System.Management.Automation.PSCredential("runneradmin", $securePassword)

          # Perform clicks using Google Chrome
          (1..5) | ForEach-Object {
              # Simulate a click at the center-right of the screen
              Add-Type -AssemblyName System.Windows.Forms

              # Explicitly cast the screen dimensions to [double] before performing the division
              $screenWidth = [double]([System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Width)
              $screenHeight = [double]([System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Height)
              
              [System.Windows.Forms.Cursor]::Position = New-Object System.Drawing.Point(($screenWidth * 3) / 4, ($screenHeight / 2))

              # Start Google Chrome with the specified URL
              Start-Process "C:\Program Files\Google\Chrome\Application\chrome.exe" -ArgumentList "--start-maximized", "https://movievip.pages.dev/home"

              # Wait for 5 seconds for the page to load
              Start-Sleep -Seconds 5

              # Simulate pressing the Enter key
              [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")

              # Wait for 3 seconds before the next click
              Start-Sleep -Seconds 3
          }
